// Code generated by Kitex v0.9.1. DO NOT EDIT.

package shortlinkservice

import (
	"context"
	shortlink "github.com/FinnTew/FinnEcommerce/src/internal/service/shortlink/kitex_gen/shortlink"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateShortLink(ctx context.Context, Req *shortlink.CreateShortLinkRequest, callOptions ...callopt.Option) (r *shortlink.CreateShortLinkResponse, err error)
	GetLongLink(ctx context.Context, Req *shortlink.GetLongLinkRequest, callOptions ...callopt.Option) (r *shortlink.GetLongLinkResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kShortLinkServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kShortLinkServiceClient struct {
	*kClient
}

func (p *kShortLinkServiceClient) CreateShortLink(ctx context.Context, Req *shortlink.CreateShortLinkRequest, callOptions ...callopt.Option) (r *shortlink.CreateShortLinkResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateShortLink(ctx, Req)
}

func (p *kShortLinkServiceClient) GetLongLink(ctx context.Context, Req *shortlink.GetLongLinkRequest, callOptions ...callopt.Option) (r *shortlink.GetLongLinkResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLongLink(ctx, Req)
}
