// Code generated by Kitex v0.9.1. DO NOT EDIT.

package shortlinkservice

import (
	shortlink "github.com/FinnTew/FinnEcommerce/src/internal/client/kitex_gen/shortlink"
	server "github.com/cloudwego/kitex/server"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler shortlink.ShortLinkService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
